#!/usr/bin/env python3

import sys
import string

from re_to_nfa import parser
from nfa import NFA, match


def main(arguments=sys.argv[1:]):
    accept, nfa, real_table = parser(arguments[0])
    if not accept:
        return
    #print(real_table)
    for line in sys.stdin:
        w = line.rstrip('\n')
        if match(nfa, w, real_table):
            print(w)
            #print("============================================")
    

if __name__ == '__main__':
    main()