#!/usr/bin/env python3

import sys
import string

from re_to_nfa import re_to_nfa
from nfa import NFA, match


def main(arguments=sys.argv[1:]):
    accept, nfa = re_to_nfa(arguments[0])
    if not accept:
        return
    for line in sys.stdin:
        w = line.rstrip('\n')
        if match(nfa, w):
            print(w)
    

if __name__ == '__main__':
    main()